# ----------------------------------------------------------------------------
#  Copyright (c) 2018 WSO2, Inc. http://www.wso2.org
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ----------------------------------------------------------------------------

wso2_group: wso2
wso2_user: wso2carbon
product_name: wso2am
product_version: "{{ version }}"
target: /mnt
product_package_location: files
backup_dir: /tmp
misc_file_location: "{{ product_package_location }}/misc"
misc_file_copy_location: "{{ target }}/misc"
security_file_location: "{{ product_package_location }}/security"
jdbc_driver: mysql-connector-java-5.1.48.jar

# Set backup_enabled to true to backup <carbon-home>/repository/deployment/server directory
backup_enabled: false

# Performance tuning configurations
enable_performance_tuning: false
performance_tuning_file_list:
  - { src: '{{ product_package_location }}/system/etc/sysctl.conf',
      dest: '/etc/sysctl.conf' }
  - { src: '{{ product_package_location }}/system/etc/security/limits.conf',
      dest: '/etc/security/limits.conf' }

# If custom keystores and trsustrores are need to be added, uncomment the below list
# Add the required files under files/security/<product-home>/<path-to-file>
# A sample is given below
security_file_list:
 - { src: '{{ security_file_location }}/wso2am/client-truststore.jks',
     dest: '{{ carbon_home }}/repository/resources/security/client-truststore.jks' }
 - { src: '{{ security_file_location }}/wso2am/wso2carbon.jks',
     dest: '{{ carbon_home }}/repository/resources/security/wso2carbon.jks' }

lb_security_file_list:
 - { src: '{{ security_file_location }}/wso2am/wso2carbon.crt',
     dest: '/home/ubuntu/keys/wso2carbon.crt' }
 - { src: '{{ security_file_location }}/wso2am/wso2carbon.key',
     dest: '/home/ubuntu/keys//wso2carbon.key' }

# Uncomment and add any miscellaneous files you need to copy
# A sample is given below
# misc_file_list:
#   - { src: '{{ misc_file_location }}/apimcli.zip',
#       dest: '{{ misc_file_copy_location }}/apimcli.zip' }

# Set the location the product packages should reside in (eg: "local" in the /files directory, "remote" in a remote location)
pack_location: local
#pack_location: remote
#remote_jdk: "<URL_TO_JDK_FILE>"
#remote_pack: "<URL_TO_APIM_PACK>"

# JDK Distributions
#jdk_name: jdk1.8.0_161
jdk_name: jdk-11
java_dir: /opt
java_symlink: "/usr/bin/java"
java_home: "{{ java_dir }}/{{ jdk_name }}"

deployment_mode: single # Single or HA

# Enable analytics for API Manager
analytics_enabled: true
stream_processor_username: ${admin.username}
stream_processor_password: ${admin.password}
stream_processor_rest_api_url: https://analyticslb.apimha.com
stream_processor_rest_api_username: ${admin.username}
stream_processor_rest_api_password: ${admin.password}
analytics_url_group:
  - analytics_urls:
      - tcp://analytics1.apimha.com:7612
#      - tcp://analytics2.apimha.com:7612
    analytics_auth_urls:
      - ssl://analytics1.apimha.com:7712
#      - ssl://analytics2.apimha.com:7712

# Server URL of the Authentication service. Make sure to import the Key Manager's public certificate to WSO2 API-M's
# client-truststore.jks. For more information, see https://docs.wso2.com/display/ADMIN44x/Creating+New+Keystores
key_manager_server_url: https://kmlb.apimha.com/services/

# API Store related configurations
api_devportal_url: https://portals.apimha.com/devportal
api_devportal_server_url: https://dev.apimha.com/services/
oauth_configs_revoke_api_url: https://kmlb.apimha.com/oauth2/revoke

# Gateway configurations
gateway_environments:
  - { type: 'hybrid',
      name: 'Production and Sandbox',
      description: 'This is a hybrid gateway that handles both production and sandbox token traffic.',
      service_url: 'https://gwlb.apimha.com/services/',
      ws_endpoint: 'ws://gw1.apimha.com:9099',
      wss_endpoint: 'wss://gw1.apimha.com:8099',
      http_endpoint: 'http://apis.apimha.com',
      https_endpoint: 'https://apis.apimha.com'
  }

# Traffic Manager configurations
throttle_config_policy_deployer_url: https://tmlb.apimha.com/services/

throttle_decision_endpoints:
  - tcp://tm1.apimha.com:5683
  - tcp://tm2.apimha.com:5683
throttling_url_group:
  - traffic_manager_urls:
      - tcp://tm1.apimha.com:9622
    traffic_manager_auth_urls:
      - ssl://tm1.apimha.com:9722
  - traffic_manager_urls:
      - tcp://tm2.apimha.com:9622
    traffic_manager_auth_urls:
      - ssl://tm2.apimha.com:9722

# event hub
eventhub_service_url: https://tm1.apimha.com:9454
eventhub_decision_endpoints:
  - tcp://tm1.apimha.com:5683
eventhub_url_group:
  - urls:
      - tcp://tm1.apimha.com:9622
    auth_urls:
      - ssl://tm1.apimha.com:9722

# Workflow configurations
workflow_enable: "false"
workflow_service_url: https://localhost:9445/bpmn
workflow_callback_endpoint: https://localhost:9443/api/am/publisher/v0.15/workflows/update-workflow-status
workflow_token_endpoint: https://localhost:8243/token
workflow_client_registration_endpoint: https://localhost:9443/client-registration/v0.15/register
workflow_server_url: https://dev1.apimha.com:9445/services/

# Datasource configurations
wso2am_db_type: mysql
wso2am_db_url: jdbc:mysql://db.apimha.com:3306/amdb?useSSL=false
wso2am_db_username: amuser
wso2am_db_password: Pass@123
wso2am_db_validation_query: SELECT 1

wso2shared_db_type: mysql
wso2shared_db_url: jdbc:mysql://db.apimha.com:3306/sharedDB?useSSL=false
wso2shared_db_username: amuser
wso2shared_db_password: Pass@123
wso2shared_db_validation_query: SELECT 1

# Key Store and Trust Store configuration
key_store_location: wso2carbon.jks
key_store_password: wso2carbon
key_store_key_password: wso2carbon
key_store_key_alias: wso2carbon
trust_store_location: client-truststore.jks
trust_store_password: wso2carbon

# The KeyStore which is used for encrypting/decrypting internal data. This block is read by Carbon Crypto Service
internal_keystore_location: wso2carbon.jks
internal_keystore_key_password: wso2carbon
internal_keystore_password: wso2carbon
internal_keystore_key_alias: wso2carbon

# Add any new changes you want to add for the group/profile below.
# If you add a new file under templates and parameterized the file, the values for those parameters should be added
# below. An example is provided below.
# Changes applied to axis2.xml file.
# clustering_enable: false

recommendations_api: https://gateway.api.cloud.wso2.com/t/aiapis/recommendations-test/1.0.0
recommendations_consumer_key: VMKfk6cdWxviMya6XN0mlrLek_4a
recommendations_consumer_secret: TI2Zku5vjValgp3VwuhdgT65YL8a
